version: "3.8"

services:
  backend:
    build: .
    container_name: express_app
    ports:
      - "8080:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydatabase"
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "node", "server.js" ]

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
